replicaCount: 1
image:
  repository: ghcr.io/alexalvarezgallardo-github/bff-service
  tag: c02991487bc541c4331fbb54f40e2f9df7cddd03
imagePullSecrets:
  - name: ghcr-pull

config:
  SPRING_PROFILES_ACTIVE: "dev"
  SPRING_DATA_REDIS_HOST: "redis"
  SPRING_DATA_REDIS_PORT: "6379"
  SPRING_SESSION_STORE_TYPE: "redis"
  AEGIS_IDENTITY_SERVICE_URL: "http://identity-dev:8081"
  AEGIS_WALLET_SERVICE_URL: "http://wallet-dev:8083"
  MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS: "always"
  OTLP_TRACING_ENDPOINT: "http://tempo.monitoring.svc:4318/v1/traces"
  MANAGEMENT_METRICS_TAGS_APPLICATION: "aegis-bff"

resources:
  limits:
    cpu: 500m
    memory: 768Mi
  requests:
    cpu: 250m
    memory: 384Mi

autoscaling:
  enabled: False
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80

podDisruptionBudget:
  enabled: False
  minAvailable: 1

affinity: {}
