replicaCount: 1
imagePullSecrets:
  - name: ghcr-pull

config:
  PROXY_API_URL: "http://bff-service"

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

autoscaling:
  enabled: False
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80

podDisruptionBudget:
  enabled: False
  minAvailable: 1

affinity: {}
nginx:
  upstream: bff-dev
  port: 8082