replicaCount: 1
imagePullSecrets:
  - name: ghcr-pull

config:
  SPRING_PROFILES_ACTIVE: "dev"
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres-identity:5432/aegis_identity"
  SPRING_DATASOURCE_USERNAME: "aegis"
  SPRING_DATASOURCE_PASSWORD: "aegis_secret"

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

autoscaling:
  enabled: False
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80

podDisruptionBudget:
  enabled: False
  minAvailable: 1

affinity: {}