apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: aegis-dev
resources:
  - ../../base
configMapGenerator:
  - name: aegis-dev-values
    files:
      - identity-values.yaml
      - wallet-values.yaml
      - bff-values.yaml
      - frontend-values.yaml
      - audit-values.yaml
      - fraud-values.yaml
      - reporting-values.yaml
      - payment-values.yaml