apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: aegis-dev
resources:
  - ../../base
  - namespace.yaml
images:
  - name: ghcr.io/alexalvarezgallardo-github/identity-service
    newTag: 42d690b98f1f7141df432122a54442590fe5133e
  - name: ghcr.io/alexalvarezgallardo-github/wallet-service
    newTag: 42d690b98f1f7141df432122a54442590fe5133e
  - name: ghcr.io/alexalvarezgallardo-github/bff-service
    newTag: 42d690b98f1f7141df432122a54442590fe5133e
  - name: ghcr.io/alexalvarezgallardo-github/frontend
    newTag: 42d690b98f1f7141df432122a54442590fe5133e