apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: aegis-dev
resources:
  - ../../base
  - namespace.yaml
images:
  - name: ghcr.io/alexalvarezgallardo-github/identity-service
    newTag: 47bb5bf4a18fd23d3064462e2927621642ebbfba
  - name: ghcr.io/alexalvarezgallardo-github/wallet-service
    newTag: 47bb5bf4a18fd23d3064462e2927621642ebbfba
  - name: ghcr.io/alexalvarezgallardo-github/bff-service
    newTag: 47bb5bf4a18fd23d3064462e2927621642ebbfba
  - name: ghcr.io/alexalvarezgallardo-github/frontend
    newTag: 47bb5bf4a18fd23d3064462e2927621642ebbfba