replicaCount: 1
image:
  repository: ghcr.io/alexalvarezgallardo-github/reporting-service
  tag: 261a1b1247d333d2cd342a0dad7fd38ba5273f1a
imagePullSecrets:
  - name: ghcr-pull

config:
  SPRING_PROFILES_ACTIVE: "dev"
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres-reporting:5432/aegis_reporting"
  SPRING_DATASOURCE_USERNAME: "aegis"
  SPRING_DATASOURCE_PASSWORD: "aegis_secret"
  SPRING_KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
  MANAGEMENT_HEALTH_KAFKA_ENABLED: "false"
  MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS: "always"
  OTLP_TRACING_ENDPOINT: "http://tempo.monitoring.svc:4318/v1/traces"
  MANAGEMENT_METRICS_TAGS_APPLICATION: "aegis-reporting-service"

resources:
  limits:
    cpu: 500m
    memory: 768Mi
  requests:
    cpu: 250m
    memory: 384Mi

autoscaling:
  enabled: False
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80

podDisruptionBudget:
  enabled: False
  minAvailable: 1

affinity: {}
