{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "reporting.fullname" . }}
  labels:
    {{- include "reporting.labels" . | nindent 4 }}
{{- end }}
