apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# Argo CD installation base (official upstream manifests).
resources:
  - github.com/argoproj/argo-cd/manifests/cluster-install?ref=v2.12.3
namespace: argocd
