apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: aegis-pre
resources:
  - ../../base
configMapGenerator:
  - name: aegis-pre-values
    files:
      - identity-values.yaml
      - wallet-values.yaml
      - bff-values.yaml
      - frontend-values.yaml