apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: aegis-stage
resources:
  - ../../base
configMapGenerator:
  - name: aegis-stage-values
    files:
      - identity-values.yaml
      - wallet-values.yaml
      - bff-values.yaml
      - frontend-values.yaml